### ISSUE TITLE
Require Chromium backend

### ISSUE THREAD

**Issue by jiri-janousek** [a-m-s/nuvola-app-bbc-iplayer#10]
Hello @a-m-s, could you modify the metadata to require the Chromium backend and test it again? I've recently implemented URL filtering for it, so it might break something.

```
"requirements": "Chromium[65] Codec[H264] Codec[MP3] Feature[MSE] Feature[Flash]",
```

**Comment by a-m-s** [comment]
It seems fine. I haven't set any "allowed_uri" yet, but probably I should.

**Comment by a-m-s** [comment]
I've set an allowed_uri, but it does not appear to be effective. Otherwise all is well. I've not had much time to work on this stuff, but I have been using it to watch TV.

**Comment by jiri-janousek** [comment]
> I've set an allowed_uri, but it does not appear to be effective.

The URL filtering happens in the App Runner process, which reads `metadata.json` only once on start-up. Could you double check that you ran `./configure` after the modification of `metadata.in.js` and then started a fresh Nuvola instance? If it still does not work, please create a bug report with a debugging log.
