### ISSUE TITLE
Test with Chromium backend

### ISSUE THREAD

**Issue by jiri-janousek** [a-m-s/nuvola-app-bbc-iplayer#8]
Hello @a-m-s, more work to do ;-)

* I would like to switch from WebKitGTK to Chromium backend for all services that require MSE - tiliado/nuvolaruntime#372
* BBC World Service seems to work (albeit with no metadata), but other content is not available outside the UK.

How to get Chromium backend:

* Chromium backend is available in the master branch of Nuvola ADK, but the default one is still WebKitGTK.
* You can `export NUVOLA_USE_CEF=true` to make Chromium the default.
* `flatpak run --env=NUVOLA_USE_CEF=true eu.tiliado.NuvolaAppBbcIplayer//master -D` also works.

What to focus on:

- Does music playback work?
- Are the web pages loaded and rendered correctly?
- Are the details shown in the developer sidebar correct?
- Do the Nuvola features you usually use work?
- Is there any difference in the responsiveness of the web page between Nuvola/WebKit, Nuvola/Chromium and Google Chrome 63?
- Can you compare memory and CPU usage of Nuvola/WebKit, Nuvola/Chromium and Google Chrome 63?

**Comment by a-m-s** [comment]
The second recipe running the `eu.tiliado.NuvolaAppBbcIplayer//master` flatpak works perfectly! :-)

There's no trouble with the flash player or HTML5 opt-in (which seems to have stopped working in the webkit version).

Also, live TV and radio now works, where only catch-up programmes worked before. It's also much less crashy.

I can't seem to get the ADK recipe to work though? I installed the master branch, ran the ADK shell, set the environment variable, and ran `nuvola -A <dir> -a bbc_iplayer`, but it just uses webkit as before. I must be doing something wrong.

**Comment by a-m-s** [comment]
(I'll get to the other questions later.)

**Comment by a-m-s** [comment]
Full screen video only fills the Nuvola window, not the whole screen.

**Comment by jiri-janousek** [comment]
>  [...] but it just uses webkit as before.

I forgot to mention that you have to remove the "WebKitGTK[2.15.3]" requirement from metadata.json - look at [the cef branch](https://github.com/tiliado/nuvola-app-bbc-iplayer/tree/cef).
> Full screen video only fills the Nuvola window, not the whole screen.

Reticketed as https://github.com/tiliado/valacef/issues/7

**Comment by a-m-s** [comment]
I'm not sure how to best compare the memory usage when chrome has so many processes, and many of them probably share some of the apparent memory usage. Both use a lot; gigabytes of virtual memory.

The performance difference between WebKit and Chromium is vast. The WebKit version barely works. It often hangs up, spinners spin forever, and live streams don't work at all. The Chromium version just works, and works fast.

The only usage issue I've noticed so far is the full-screen thing. The integration appears just fine.

**Comment by jiri-janousek** [comment]
> I'm not sure how to best compare the memory usage when chrome has so many processes, and many of them probably share some of the apparent memory usage.

Launch Chrome with only a single tab with BBC iPlayer and then sum up all Chrome processes in GNOME system monitor. Then sum up all Nuvola's processes (e.g. nuvola-app-whatever, ValacefSubprocess, eu.tiliado.Nuvola, nuvola, etc.).

> Both use a lot; gigabytes of virtual memory.

Virtual memory does not really matter. If you use `ps aux`, look at the RSS column.

> The integration appears just fine.

BBC World Service didn't work for me. I'll try again.

**Comment by a-m-s** [comment]
Yeah I didn't get around to the World service yet. The region locked stuff I use is fine.

**Comment by a-m-s** [comment]
You could try the news videos. Those used to work.

**Comment by a-m-s** [comment]
I've still not found a satisfactory way to read the true memory usage for a multi-process application, however, the sum of the "memory" sdfs from the system monitor are as follows:

eu.tiliado.NuvolaAdk + descendants: 294MB
chrome + descendants: 1230MB

In both cases the browser was on the same page, with the same video paused at around the same spot.

However, it's probably an unfair comparison because chrome is running some extensions. Besides which, I'm pretty sure that the processes within the application will be sharing some of that memory, so some of it will have been double accounted.

I've not given numbers for the WebKitGTK memory usage because the website did not work well in that browser, and how efficiently it didn't run it is not that interesting.

**Comment by a-m-s** [comment]
Have I covered all your questions?

**Comment by jiri-janousek** [comment]
That's all, thanks :-)
