### ISSUE TITLE
Release 1.4

### ISSUE THREAD

**Issue by jiri-janousek** [a-m-s/nuvola-app-bbc-iplayer#9]
Hello @a-m-s. Could you prepare this script for a new release? Thanks :-)

* Remove trailing whitespace from metadata.in.json (a bug in Nuvola SDK).
* Convert with `standard`.
* Update copyright year.
* Remove `@API 4.5` comments.

**Comment by a-m-s** [comment]
This should be complete now.

I've updated the live TV integration too, which seems to have changed recently.

**Comment by jiri-janousek** [comment]
Great :+1: Please keep this open until I actually make the release.
